// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// iterativeMortality
SEXP iterativeMortality(SEXP rMj, SEXP radd, SEXP rw, SEXP rN, SEXP rYso, int rniter);
RcppExport SEXP _mice_iterativeMortality(SEXP rMjSEXP, SEXP raddSEXP, SEXP rwSEXP, SEXP rNSEXP, SEXP rYsoSEXP, SEXP rniterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type rMj(rMjSEXP);
    Rcpp::traits::input_parameter< SEXP >::type radd(raddSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rw(rwSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rN(rNSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rYso(rYsoSEXP);
    Rcpp::traits::input_parameter< int >::type rniter(rniterSEXP);
    rcpp_result_gen = Rcpp::wrap(iterativeMortality(rMj, radd, rw, rN, rYso, rniter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mice_iterativeMortality", (DL_FUNC) &_mice_iterativeMortality, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_mice(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
