# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getStartM <- function(N, w, delta, dt, Ystar, access) {
    .Call(`_mice_getStartM`, N, w, delta, dt, Ystar, access)
}

iterativeMortality <- function(Mj, add, w, N, Yso, niter) {
    .Call(`_mice_iterativeMortality`, Mj, add, w, N, Yso, niter)
}

iterativeMortalityF <- function(N, w, delta, dt, Ystar, access, F, add, Mstarv, eta_crit, niter) {
    .Call(`_mice_iterativeMortalityF`, N, w, delta, dt, Ystar, access, F, add, Mstarv, eta_crit, niter)
}

