# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

iterativeMortality <- function(rMj, radd, rw, rN, rYso, rniter) {
    .Call(`_mice_iterativeMortality`, rMj, radd, rw, rN, rYso, rniter)
}

